# Generated by Django 3.2.6 on 2021-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sportwear'), ('OW', 'Outwear'), ('A', 'Accessory'), ('T', 'Tech'), ('D', 'Decorations')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(),
        ),
    ]
