# Generated by Django 3.2.6 on 2021-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211107_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sportwear'), ('OW', 'Outwear'), ('A', 'Accessory'), ('T', 'Tech'), ('D', 'Decorations'), ('KT', "Kid's toy"), ('F', 'Food')], max_length=2),
        ),
    ]
